window.ROAD_TEST_QUESTION_BANK_SEEDED = [
  {
    "bankId": "RT-001",
    "segmentId": "road-seg-001",
    "moduleId": "vehicle_exterior_check",
    "moduleTitle": "車外安全檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "(車輛檢查)從左前輪開始， 雙手壓輪胎，口誦【胎紋、胎壓正常】",
    "captionText": "(車輛檢查)從左前輪開始， 雙手壓輪胎，口誦【胎紋、胎壓正常】",
    "startSec": 0.66,
    "endSec": 5.66,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 0.0,
    "clipEndSec": 6.66,
    "tags": [
      "tire_check"
    ],
    "moduleSummary": "依逆時針方向完成四輪、燈具與車底檢查，建立固定巡檢順序。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-002",
    "segmentId": "road-seg-002",
    "moduleId": "vehicle_exterior_check",
    "moduleTitle": "車外安全檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "查看左右車燈，【車燈無破損】 蹲下看車底，【車底無異物】",
    "captionText": "查看左右車燈，【車燈無破損】 蹲下看車底，【車底無異物】",
    "startSec": 5.66,
    "endSec": 10.766,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 4.66,
    "clipEndSec": 11.766,
    "tags": [
      "light_check",
      "underbody_check"
    ],
    "moduleSummary": "依逆時針方向完成四輪、燈具與車底檢查，建立固定巡檢順序。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-003",
    "segmentId": "road-seg-003",
    "moduleId": "vehicle_exterior_check",
    "moduleTitle": "車外安全檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "檢查右前輪，雙手壓輪胎， 【胎紋、胎壓正常】 蹲下【車底無異物】",
    "captionText": "檢查右前輪，雙手壓輪胎， 【胎紋、胎壓正常】 蹲下【車底無異物】",
    "startSec": 10.766,
    "endSec": 20.0,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 9.766,
    "clipEndSec": 21.0,
    "tags": [
      "tire_check",
      "underbody_check"
    ],
    "moduleSummary": "依逆時針方向完成四輪、燈具與車底檢查，建立固定巡檢順序。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-004",
    "segmentId": "road-seg-004",
    "moduleId": "vehicle_exterior_check",
    "moduleTitle": "車外安全檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "檢查右後輪，【胎紋、胎壓正常】",
    "captionText": "檢查右後輪，【胎紋、胎壓正常】",
    "startSec": 20.0,
    "endSec": 25.836,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 19.0,
    "clipEndSec": 26.836,
    "tags": [
      "tire_check"
    ],
    "moduleSummary": "依逆時針方向完成四輪、燈具與車底檢查，建立固定巡檢順序。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-005",
    "segmentId": "road-seg-005",
    "moduleId": "vehicle_exterior_check",
    "moduleTitle": "車外安全檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "檢查左右車燈，【車燈無破損】； 蹲下看車底，【車底無異物】",
    "captionText": "檢查左右車燈，【車燈無破損】； 蹲下看車底，【車底無異物】",
    "startSec": 25.836,
    "endSec": 31.955,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 24.836,
    "clipEndSec": 32.955,
    "tags": [
      "light_check",
      "underbody_check"
    ],
    "moduleSummary": "依逆時針方向完成四輪、燈具與車底檢查，建立固定巡檢順序。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-006",
    "segmentId": "road-seg-006",
    "moduleId": "vehicle_exterior_check",
    "moduleTitle": "車外安全檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "檢查左後輪，【胎紋、胎壓正常】； 蹲下看車底，【車底無異物】",
    "captionText": "檢查左後輪，【胎紋、胎壓正常】； 蹲下看車底，【車底無異物】",
    "startSec": 31.955,
    "endSec": 36.696,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 30.955,
    "clipEndSec": 37.696,
    "tags": [
      "tire_check",
      "underbody_check"
    ],
    "moduleSummary": "依逆時針方向完成四輪、燈具與車底檢查，建立固定巡檢順序。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-007",
    "segmentId": "road-seg-007",
    "moduleId": "two_stage_door_entry",
    "moduleTitle": "兩段式開車門上車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "口誦【兩段式開車門】先看左、看右，確認【左右無來車】",
    "captionText": "口誦【兩段式開車門】先看左、看右，確認【左右無來車】",
    "startSec": 36.696,
    "endSec": 44.169,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 35.696,
    "clipEndSec": 45.169,
    "tags": [
      "safe_left_right"
    ],
    "moduleSummary": "先短開門再複查，確認左右無來車後再開至上車角度。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-008",
    "segmentId": "road-seg-008",
    "moduleId": "two_stage_door_entry",
    "moduleTitle": "兩段式開車門上車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "車門先開約15公分，身體不轉動， 再看左、看右確認【左右無來車】後， 再開至約45度上車",
    "captionText": "車門先開約15公分，身體不轉動， 再看左、看右確認【左右無來車】後， 再開至約45度上車",
    "startSec": 44.169,
    "endSec": 54.177,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 43.169,
    "clipEndSec": 55.177,
    "tags": [
      "safe_left_right"
    ],
    "moduleSummary": "先短開門再複查，確認左右無來車後再開至上車角度。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-009",
    "segmentId": "road-seg-009",
    "moduleId": "cockpit_setup_and_engine_start",
    "moduleTitle": "車內調整與發動前檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "車內：口誦【調整座椅】【調整椅背】【調整頭枕】",
    "captionText": "車內：口誦【調整座椅】【調整椅背】【調整頭枕】",
    "startSec": 54.177,
    "endSec": 65.19,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 53.177,
    "clipEndSec": 66.19,
    "tags": [],
    "moduleSummary": "完成座椅鏡面與安全帶設定，再做紅火、儀表板、煞車與方向燈確認。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-010",
    "segmentId": "road-seg-010",
    "moduleId": "cockpit_setup_and_engine_start",
    "moduleTitle": "車內調整與發動前檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【繫上安全帶】【調整中央後照鏡、左右後照鏡】【確定檔位在P檔、手煞車已拉起】",
    "captionText": "【繫上安全帶】【調整中央後照鏡、左右後照鏡】【確定檔位在P檔、手煞車已拉起】",
    "startSec": 65.19,
    "endSec": 83.033,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 64.19,
    "clipEndSec": 84.033,
    "tags": [
      "gear_p",
      "hand_brake"
    ],
    "moduleSummary": "完成座椅鏡面與安全帶設定，再做紅火、儀表板、煞車與方向燈確認。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-011",
    "segmentId": "road-seg-011",
    "moduleId": "cockpit_setup_and_engine_start",
    "moduleTitle": "車內調整與發動前檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "鑰匙往外轉【開啟紅火】",
    "captionText": "鑰匙往外轉【開啟紅火】",
    "startSec": 83.033,
    "endSec": 89.773,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 82.033,
    "clipEndSec": 90.773,
    "tags": [
      "ignition_on"
    ],
    "moduleSummary": "完成座椅鏡面與安全帶設定，再做紅火、儀表板、煞車與方向燈確認。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-012",
    "segmentId": "road-seg-012",
    "moduleId": "cockpit_setup_and_engine_start",
    "moduleTitle": "車內調整與發動前檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【油量、溫度、引擎、電瓶、手煞車燈、機油 正常】",
    "captionText": "【油量、溫度、引擎、電瓶、手煞車燈、機油 正常】",
    "startSec": 89.773,
    "endSec": 101.697,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 88.773,
    "clipEndSec": 102.697,
    "tags": [
      "hand_brake"
    ],
    "moduleSummary": "完成座椅鏡面與安全帶設定，再做紅火、儀表板、煞車與方向燈確認。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-013",
    "segmentId": "road-seg-013",
    "moduleId": "cockpit_setup_and_engine_start",
    "moduleTitle": "車內調整與發動前檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "踩煞車、發動引擎，口誦 【引擎發動：儀表板正常】",
    "captionText": "踩煞車、發動引擎，口誦 【引擎發動：儀表板正常】",
    "startSec": 101.697,
    "endSec": 107.723,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 100.697,
    "clipEndSec": 108.723,
    "tags": [
      "engine_start"
    ],
    "moduleSummary": "完成座椅鏡面與安全帶設定，再做紅火、儀表板、煞車與方向燈確認。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-014",
    "segmentId": "road-seg-014",
    "moduleId": "cockpit_setup_and_engine_start",
    "moduleTitle": "車內調整與發動前檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "開風扇 開AC； (發動後只會剩手煞車燈亮著)",
    "captionText": "開風扇 開AC； (發動後只會剩手煞車燈亮著)",
    "startSec": 107.723,
    "endSec": 112.89,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 106.723,
    "clipEndSec": 113.89,
    "tags": [
      "hand_brake"
    ],
    "moduleSummary": "完成座椅鏡面與安全帶設定，再做紅火、儀表板、煞車與方向燈確認。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-015",
    "segmentId": "road-seg-015",
    "moduleId": "cockpit_setup_and_engine_start",
    "moduleTitle": "車內調整與發動前檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "口誦【試踩煞車：煞車正常】",
    "captionText": "口誦【試踩煞車：煞車正常】",
    "startSec": 112.89,
    "endSec": 117.89,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 111.89,
    "clipEndSec": 118.89,
    "tags": [],
    "moduleSummary": "完成座椅鏡面與安全帶設定，再做紅火、儀表板、煞車與方向燈確認。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-016",
    "segmentId": "road-seg-016",
    "moduleId": "cockpit_setup_and_engine_start",
    "moduleTitle": "車內調整與發動前檢查",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "口誦【試打左右方向燈：方向燈正常】",
    "captionText": "口誦【試打左右方向燈：方向燈正常】",
    "startSec": 117.89,
    "endSec": 123.89,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 116.89,
    "clipEndSec": 124.89,
    "tags": [
      "right_signal"
    ],
    "moduleSummary": "完成座椅鏡面與安全帶設定，再做紅火、儀表板、煞車與方向燈確認。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-017",
    "segmentId": "road-seg-017",
    "moduleId": "start_and_initial_turns",
    "moduleTitle": "起步與前段轉彎",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "打左方向燈，口誦【準備起步，打D檔，放手煞車】",
    "captionText": "打左方向燈，口誦【準備起步，打D檔，放手煞車】",
    "startSec": 123.89,
    "endSec": 131.835,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 122.89,
    "clipEndSec": 132.835,
    "tags": [
      "left_signal",
      "gear_d",
      "hand_brake"
    ],
    "moduleSummary": "左方向燈起步、完成起駛觀察後右轉，再於下一路口左轉切入快車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-018",
    "segmentId": "road-seg-018",
    "moduleId": "start_and_initial_turns",
    "moduleTitle": "起步與前段轉彎",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "起駛前轉頭查看前後左右， 口誦【左右無來車，後方無來車】",
    "captionText": "起駛前轉頭查看前後左右， 口誦【左右無來車，後方無來車】",
    "startSec": 131.835,
    "endSec": 144.424,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 130.835,
    "clipEndSec": 145.424,
    "tags": [
      "safe_left_right",
      "rear_clear"
    ],
    "moduleSummary": "左方向燈起步、完成起駛觀察後右轉，再於下一路口左轉切入快車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-019",
    "segmentId": "road-seg-019",
    "moduleId": "start_and_initial_turns",
    "moduleTitle": "起步與前段轉彎",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "方向燈回正，打右邊方向燈",
    "captionText": "方向燈回正，打右邊方向燈",
    "startSec": 149.46,
    "endSec": 154.632,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 148.46,
    "clipEndSec": 155.632,
    "tags": [],
    "moduleSummary": "左方向燈起步、完成起駛觀察後右轉，再於下一路口左轉切入快車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-020",
    "segmentId": "road-seg-020",
    "moduleId": "start_and_initial_turns",
    "moduleTitle": "起步與前段轉彎",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "前方路口減速查看；",
    "captionText": "前方路口減速查看；",
    "startSec": 154.632,
    "endSec": 158.551,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 153.632,
    "clipEndSec": 159.551,
    "tags": [
      "intersection_scan"
    ],
    "moduleSummary": "左方向燈起步、完成起駛觀察後右轉，再於下一路口左轉切入快車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-021",
    "segmentId": "road-seg-021",
    "moduleId": "start_and_initial_turns",
    "moduleTitle": "起步與前段轉彎",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "(行駛時出入都靠大門左側)",
    "captionText": "(行駛時出入都靠大門左側)",
    "startSec": 158.551,
    "endSec": 176.8,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 157.551,
    "clipEndSec": 177.8,
    "tags": [],
    "moduleSummary": "左方向燈起步、完成起駛觀察後右轉，再於下一路口左轉切入快車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-022",
    "segmentId": "road-seg-022",
    "moduleId": "start_and_initial_turns",
    "moduleTitle": "起步與前段轉彎",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【左右無來車、後方無來車】 右轉後打左方向燈",
    "captionText": "【左右無來車、後方無來車】 右轉後打左方向燈",
    "startSec": 176.8,
    "endSec": 184.328,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 175.8,
    "clipEndSec": 185.328,
    "tags": [
      "left_signal",
      "safe_left_right",
      "rear_clear"
    ],
    "moduleSummary": "左方向燈起步、完成起駛觀察後右轉，再於下一路口左轉切入快車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-023",
    "segmentId": "road-seg-023",
    "moduleId": "start_and_initial_turns",
    "moduleTitle": "起步與前段轉彎",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看,左右無來車】； 左轉走快車道 此路口需特別注意雙黃線",
    "captionText": "【前方路口減速查看,左右無來車】； 左轉走快車道 此路口需特別注意雙黃線",
    "startSec": 184.328,
    "endSec": 198.949,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 183.328,
    "clipEndSec": 199.949,
    "tags": [
      "safe_left_right",
      "intersection_scan",
      "fast_lane"
    ],
    "moduleSummary": "左方向燈起步、完成起駛觀察後右轉，再於下一路口左轉切入快車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-024",
    "segmentId": "road-seg-024",
    "moduleId": "lane_change_fast_to_slow",
    "moduleTitle": "快車道切慢車道",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "打右方向燈 【前方路口減速查看，進行變換車道】 【左右無來車，後方無來車】； 由快車道切換至慢車道，轉頭時需看到B柱",
    "captionText": "打右方向燈 【前方路口減速查看，進行變換車道】 【左右無來車，後方無來車】； 由快車道切換至慢車道，轉頭時需看到B柱",
    "startSec": 198.949,
    "endSec": 221.487,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 197.949,
    "clipEndSec": 222.487,
    "tags": [
      "b_pillar",
      "fast_lane",
      "intersection_scan",
      "lane_change",
      "rear_clear",
      "right_signal",
      "safe_left_right",
      "slow_lane"
    ],
    "moduleSummary": "右方向燈加口誦後確認後方，轉頭看到B柱再由快車道切入慢車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-025",
    "segmentId": "road-seg-025",
    "moduleId": "lane_change_fast_to_slow",
    "moduleTitle": "快車道切慢車道",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "完成變換車道後，持續穩定行駛於慢車道",
    "captionText": "完成變換車道後，持續穩定行駛於慢車道",
    "startSec": 221.487,
    "endSec": 227.835,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 220.487,
    "clipEndSec": 228.835,
    "tags": [
      "lane_change",
      "slow_lane"
    ],
    "moduleSummary": "右方向燈加口誦後確認後方，轉頭看到B柱再由快車道切入慢車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-026",
    "segmentId": "road-seg-026",
    "moduleId": "roadside_temporary_stop",
    "moduleTitle": "路邊臨時停車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "打右方向燈，口誦【前方路口減速查看，左右無來車，後方無來車】；再看左後方【後方無來車】， 頭需看到B柱，車身盡量靠近道路邊線",
    "captionText": "打右方向燈，口誦【前方路口減速查看，左右無來車，後方無來車】；再看左後方【後方無來車】， 頭需看到B柱，車身盡量靠近道路邊線",
    "startSec": 227.835,
    "endSec": 250.585,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 226.835,
    "clipEndSec": 251.585,
    "tags": [
      "b_pillar",
      "intersection_scan",
      "rear_clear",
      "right_signal",
      "safe_left_right"
    ],
    "moduleSummary": "右方向燈靠邊，確認後方與邊線距離，停妥後P檔與手煞車完成臨停。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-027",
    "segmentId": "road-seg-027",
    "moduleId": "roadside_temporary_stop",
    "moduleTitle": "路邊臨時停車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "注意道路邊線不可壓到，",
    "captionText": "注意道路邊線不可壓到，",
    "startSec": 254.086,
    "endSec": 259.031,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 253.086,
    "clipEndSec": 260.031,
    "tags": [],
    "moduleSummary": "右方向燈靠邊，確認後方與邊線距離，停妥後P檔與手煞車完成臨停。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-028",
    "segmentId": "road-seg-028",
    "moduleId": "roadside_temporary_stop",
    "moduleTitle": "路邊臨時停車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "打右方向燈；",
    "captionText": "打右方向燈；",
    "startSec": 259.031,
    "endSec": 263.92,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 258.031,
    "clipEndSec": 264.92,
    "tags": [
      "right_signal"
    ],
    "moduleSummary": "右方向燈靠邊，確認後方與邊線距離，停妥後P檔與手煞車完成臨停。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-029",
    "segmentId": "road-seg-029",
    "moduleId": "roadside_temporary_stop",
    "moduleTitle": "路邊臨時停車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看，進行路邊臨時停車，左右無來車，後方無來車】， 頭需看到B柱",
    "captionText": "【前方路口減速查看，進行路邊臨時停車，左右無來車，後方無來車】， 頭需看到B柱",
    "startSec": 263.92,
    "endSec": 275.962,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 262.92,
    "clipEndSec": 276.962,
    "tags": [
      "b_pillar",
      "intersection_scan",
      "rear_clear",
      "safe_left_right",
      "temporary_stop"
    ],
    "moduleSummary": "右方向燈靠邊，確認後方與邊線距離，停妥後P檔與手煞車完成臨停。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-030",
    "segmentId": "road-seg-030",
    "moduleId": "roadside_temporary_stop",
    "moduleTitle": "路邊臨時停車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【打P檔、拉手煞車】；",
    "captionText": "【打P檔、拉手煞車】；",
    "startSec": 276.487,
    "endSec": 282.489,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 275.487,
    "clipEndSec": 283.489,
    "tags": [
      "gear_p",
      "hand_brake"
    ],
    "moduleSummary": "右方向燈靠邊，確認後方與邊線距離，停妥後P檔與手煞車完成臨停。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-031",
    "segmentId": "road-seg-031",
    "moduleId": "roadside_temporary_stop",
    "moduleTitle": "路邊臨時停車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "放鬆腳煞車，確認不滑動後， 腳再回煞車",
    "captionText": "放鬆腳煞車，確認不滑動後， 腳再回煞車",
    "startSec": 282.489,
    "endSec": 285.312,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 281.489,
    "clipEndSec": 286.312,
    "tags": [],
    "moduleSummary": "右方向燈靠邊，確認後方與邊線距離，停妥後P檔與手煞車完成臨停。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-032",
    "segmentId": "road-seg-032",
    "moduleId": "roadside_temporary_stop",
    "moduleTitle": "路邊臨時停車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【路邊臨時停車完畢】",
    "captionText": "【路邊臨時停車完畢】",
    "startSec": 285.312,
    "endSec": 288.22,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 284.312,
    "clipEndSec": 289.22,
    "tags": [
      "temporary_stop"
    ],
    "moduleSummary": "右方向燈靠邊，確認後方與邊線距離，停妥後P檔與手煞車完成臨停。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-033",
    "segmentId": "road-seg-033",
    "moduleId": "resume_and_left_lane_change",
    "moduleTitle": "由路邊切回主線並左切車道",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "踩剎車，打左方向燈 【切入主線道，打D檔，放手煞車，後方無來車】； 頭需看到B柱後再起步",
    "captionText": "踩剎車，打左方向燈 【切入主線道，打D檔，放手煞車，後方無來車】； 頭需看到B柱後再起步",
    "startSec": 288.22,
    "endSec": 305.709,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 287.22,
    "clipEndSec": 306.709,
    "tags": [
      "b_pillar",
      "gear_d",
      "hand_brake",
      "left_signal",
      "rear_clear"
    ],
    "moduleSummary": "左方向燈起步回主線，看到B柱後再左切變換車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-034",
    "segmentId": "road-seg-034",
    "moduleId": "resume_and_left_lane_change",
    "moduleTitle": "由路邊切回主線並左切車道",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "打左方向燈，口誦 【進行變換車道，後方無來車】； 頭需看到B柱，沒車再變換車道",
    "captionText": "打左方向燈，口誦 【進行變換車道，後方無來車】； 頭需看到B柱，沒車再變換車道",
    "startSec": 312.292,
    "endSec": 324.866,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 311.292,
    "clipEndSec": 325.866,
    "tags": [
      "b_pillar",
      "lane_change",
      "left_signal",
      "rear_clear"
    ],
    "moduleSummary": "左方向燈起步回主線，看到B柱後再左切變換車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-035",
    "segmentId": "road-seg-035",
    "moduleId": "straight_intersection_checks",
    "moduleTitle": "直線行駛與路口減速查看",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "前方路口減速查看，口誦【左右無來車】；",
    "captionText": "前方路口減速查看，口誦【左右無來車】；",
    "startSec": 325.374,
    "endSec": 335.325,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 324.374,
    "clipEndSec": 336.325,
    "tags": [
      "safe_left_right",
      "intersection_scan"
    ],
    "moduleSummary": "連續通過路口前都要減速查看，直線段保持車身與車道線間距。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-036",
    "segmentId": "road-seg-036",
    "moduleId": "straight_intersection_checks",
    "moduleTitle": "直線行駛與路口減速查看",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "直線路段留意兩側照後鏡與車身、車道線間距",
    "captionText": "直線路段留意兩側照後鏡與車身、車道線間距",
    "startSec": 335.325,
    "endSec": 345.9,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 334.325,
    "clipEndSec": 346.9,
    "tags": [],
    "moduleSummary": "連續通過路口前都要減速查看，直線段保持車身與車道線間距。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-037",
    "segmentId": "road-seg-037",
    "moduleId": "straight_intersection_checks",
    "moduleTitle": "直線行駛與路口減速查看",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "前方路口減速查看，口誦【左右無來車】；",
    "captionText": "前方路口減速查看，口誦【左右無來車】；",
    "startSec": 346.9,
    "endSec": 356.779,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 345.9,
    "clipEndSec": 357.779,
    "tags": [
      "safe_left_right",
      "intersection_scan"
    ],
    "moduleSummary": "連續通過路口前都要減速查看，直線段保持車身與車道線間距。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-038",
    "segmentId": "road-seg-038",
    "moduleId": "straight_intersection_checks",
    "moduleTitle": "直線行駛與路口減速查看",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "行駛中隨時注意不要壓到左右車道線",
    "captionText": "行駛中隨時注意不要壓到左右車道線",
    "startSec": 359.782,
    "endSec": 367.28,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 358.782,
    "clipEndSec": 368.28,
    "tags": [],
    "moduleSummary": "連續通過路口前都要減速查看，直線段保持車身與車道線間距。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-039",
    "segmentId": "road-seg-039",
    "moduleId": "straight_intersection_checks",
    "moduleTitle": "直線行駛與路口減速查看",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "再次通過路口前減速查看，口誦【左右無來車】",
    "captionText": "再次通過路口前減速查看，口誦【左右無來車】",
    "startSec": 368.28,
    "endSec": 376.28,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 367.28,
    "clipEndSec": 377.28,
    "tags": [
      "safe_left_right"
    ],
    "moduleSummary": "連續通過路口前都要減速查看，直線段保持車身與車道線間距。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-040",
    "segmentId": "road-seg-040",
    "moduleId": "u_turn_sequence",
    "moduleTitle": "迴轉流程",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "打左方向燈",
    "captionText": "打左方向燈",
    "startSec": 390.736,
    "endSec": 394.142,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 389.736,
    "clipEndSec": 395.142,
    "tags": [
      "left_signal"
    ],
    "moduleSummary": "左方向燈配合路口減速查看，定點後迅速操作方向盤，迴轉後走外側車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-041",
    "segmentId": "road-seg-041",
    "moduleId": "u_turn_sequence",
    "moduleTitle": "迴轉流程",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看】，配合準備迴轉",
    "captionText": "【前方路口減速查看】，配合準備迴轉",
    "startSec": 394.142,
    "endSec": 404.993,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 393.142,
    "clipEndSec": 405.993,
    "tags": [
      "intersection_scan",
      "u_turn"
    ],
    "moduleSummary": "左方向燈配合路口減速查看，定點後迅速操作方向盤，迴轉後走外側車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-042",
    "segmentId": "road-seg-042",
    "moduleId": "u_turn_sequence",
    "moduleTitle": "迴轉流程",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "確認【左右無來車】； 到達定點後迅速完成方向盤操作",
    "captionText": "確認【左右無來車】； 到達定點後迅速完成方向盤操作",
    "startSec": 405.0,
    "endSec": 413.136,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 404.0,
    "clipEndSec": 414.136,
    "tags": [
      "safe_left_right"
    ],
    "moduleSummary": "左方向燈配合路口減速查看，定點後迅速操作方向盤，迴轉後走外側車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-043",
    "segmentId": "road-seg-043",
    "moduleId": "u_turn_sequence",
    "moduleTitle": "迴轉流程",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "迴轉後走外側車道，",
    "captionText": "迴轉後走外側車道，",
    "startSec": 413.622,
    "endSec": 428.299,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 412.622,
    "clipEndSec": 429.299,
    "tags": [
      "u_turn"
    ],
    "moduleSummary": "左方向燈配合路口減速查看，定點後迅速操作方向盤，迴轉後走外側車道。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-044",
    "segmentId": "road-seg-044",
    "moduleId": "post_uturn_speed_and_centering",
    "moduleTitle": "迴轉後控速與置中",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "持續注意兩側車道線，盡量讓車輛保持在車道中央",
    "captionText": "持續注意兩側車道線，盡量讓車輛保持在車道中央",
    "startSec": 428.299,
    "endSec": 435.58,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 427.299,
    "clipEndSec": 436.58,
    "tags": [],
    "moduleSummary": "迴轉後保持在車道中央，避免壓線，並將車速維持在約40公里。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-045",
    "segmentId": "road-seg-045",
    "moduleId": "post_uturn_speed_and_centering",
    "moduleTitle": "迴轉後控速與置中",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "壓到任何一側邊線都會扣分，",
    "captionText": "壓到任何一側邊線都會扣分，",
    "startSec": 437.073,
    "endSec": 440.698,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 436.073,
    "clipEndSec": 441.698,
    "tags": [],
    "moduleSummary": "迴轉後保持在車道中央，避免壓線，並將車速維持在約40公里。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-046",
    "segmentId": "road-seg-046",
    "moduleId": "post_uturn_speed_and_centering",
    "moduleTitle": "迴轉後控速與置中",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看】【左右無來車】",
    "captionText": "【前方路口減速查看】【左右無來車】",
    "startSec": 440.698,
    "endSec": 446.58,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 439.698,
    "clipEndSec": 447.58,
    "tags": [
      "safe_left_right",
      "intersection_scan"
    ],
    "moduleSummary": "迴轉後保持在車道中央，避免壓線，並將車速維持在約40公里。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-047",
    "segmentId": "road-seg-047",
    "moduleId": "post_uturn_speed_and_centering",
    "moduleTitle": "迴轉後控速與置中",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "行車速度盡量維持在約40公里左右",
    "captionText": "行車速度盡量維持在約40公里左右",
    "startSec": 452.31,
    "endSec": 457.31,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 451.31,
    "clipEndSec": 458.31,
    "tags": [],
    "moduleSummary": "迴轉後保持在車道中央，避免壓線，並將車速維持在約40公里。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-048",
    "segmentId": "road-seg-048",
    "moduleId": "post_uturn_speed_and_centering",
    "moduleTitle": "迴轉後控速與置中",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看】【左右無來車】",
    "captionText": "【前方路口減速查看】【左右無來車】",
    "startSec": 459.31,
    "endSec": 465.31,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 458.31,
    "clipEndSec": 466.31,
    "tags": [
      "safe_left_right",
      "intersection_scan"
    ],
    "moduleSummary": "迴轉後保持在車道中央，避免壓線，並將車速維持在約40公里。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-049",
    "segmentId": "road-seg-049",
    "moduleId": "post_uturn_speed_and_centering",
    "moduleTitle": "迴轉後控速與置中",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看】【左右無來車】",
    "captionText": "【前方路口減速查看】【左右無來車】",
    "startSec": 476.26,
    "endSec": 483.26,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 475.26,
    "clipEndSec": 484.26,
    "tags": [
      "safe_left_right",
      "intersection_scan"
    ],
    "moduleSummary": "迴轉後保持在車道中央，避免壓線，並將車速維持在約40公里。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-050",
    "segmentId": "road-seg-050",
    "moduleId": "post_uturn_speed_and_centering",
    "moduleTitle": "迴轉後控速與置中",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "此路段須特別注意車速， 標示約40公里，最高速度不要超過44公里",
    "captionText": "此路段須特別注意車速， 標示約40公里，最高速度不要超過44公里",
    "startSec": 489.74,
    "endSec": 499.74,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 488.74,
    "clipEndSec": 500.74,
    "tags": [],
    "moduleSummary": "迴轉後保持在車道中央，避免壓線，並將車速維持在約40公里。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-051",
    "segmentId": "road-seg-051",
    "moduleId": "post_uturn_speed_and_centering",
    "moduleTitle": "迴轉後控速與置中",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看】【左右無來車】",
    "captionText": "【前方路口減速查看】【左右無來車】",
    "startSec": 499.74,
    "endSec": 505.374,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 498.74,
    "clipEndSec": 506.374,
    "tags": [
      "safe_left_right",
      "intersection_scan"
    ],
    "moduleSummary": "迴轉後保持在車道中央，避免壓線，並將車速維持在約40公里。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-052",
    "segmentId": "road-seg-052",
    "moduleId": "signalized_left_turn_to_slow_lane",
    "moduleTitle": "號誌路口左轉回慢車道",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "到路口前打左方向燈 【前方路口減速查看】【左右無來車】",
    "captionText": "到路口前打左方向燈 【前方路口減速查看】【左右無來車】",
    "startSec": 508.948,
    "endSec": 519.132,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 507.948,
    "clipEndSec": 520.132,
    "tags": [
      "left_signal",
      "safe_left_right",
      "intersection_scan"
    ],
    "moduleSummary": "路口前打左方向燈，等待號誌後起步要左右擺頭，左轉後直接走慢車道並留意左後方插入車。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-053",
    "segmentId": "road-seg-053",
    "moduleId": "signalized_left_turn_to_slow_lane",
    "moduleTitle": "號誌路口左轉回慢車道",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "等紅綠燈後，起步前記得做左右擺頭； 尤其是第一台",
    "captionText": "等紅綠燈後，起步前記得做左右擺頭； 尤其是第一台",
    "startSec": 519.132,
    "endSec": 555.352,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 518.132,
    "clipEndSec": 556.352,
    "tags": [],
    "moduleSummary": "路口前打左方向燈，等待號誌後起步要左右擺頭，左轉後直接走慢車道並留意左後方插入車。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-054",
    "segmentId": "road-seg-054",
    "moduleId": "signalized_left_turn_to_slow_lane",
    "moduleTitle": "號誌路口左轉回慢車道",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "口誦【左右無來車，後方無來車】；頭需看到B柱",
    "captionText": "口誦【左右無來車，後方無來車】；頭需看到B柱",
    "startSec": 555.584,
    "endSec": 565.729,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 554.584,
    "clipEndSec": 566.729,
    "tags": [
      "b_pillar",
      "safe_left_right",
      "rear_clear"
    ],
    "moduleSummary": "路口前打左方向燈，等待號誌後起步要左右擺頭，左轉後直接走慢車道並留意左後方插入車。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-055",
    "segmentId": "road-seg-055",
    "moduleId": "signalized_left_turn_to_slow_lane",
    "moduleTitle": "號誌路口左轉回慢車道",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "左轉後直接走慢車道，",
    "captionText": "左轉後直接走慢車道，",
    "startSec": 565.729,
    "endSec": 569.313,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 564.729,
    "clipEndSec": 570.313,
    "tags": [
      "slow_lane"
    ],
    "moduleSummary": "路口前打左方向燈，等待號誌後起步要左右擺頭，左轉後直接走慢車道並留意左後方插入車。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-056",
    "segmentId": "road-seg-056",
    "moduleId": "signalized_left_turn_to_slow_lane",
    "moduleTitle": "號誌路口左轉回慢車道",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "注意左側可能有違規插入的車輛，確認左後方來車",
    "captionText": "注意左側可能有違規插入的車輛，確認左後方來車",
    "startSec": 569.313,
    "endSec": 574.9,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 568.313,
    "clipEndSec": 575.9,
    "tags": [],
    "moduleSummary": "路口前打左方向燈，等待號誌後起步要左右擺頭，左轉後直接走慢車道並留意左後方插入車。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-057",
    "segmentId": "road-seg-057",
    "moduleId": "return_and_finish_stop",
    "moduleTitle": "回起終點與收車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看】【左右無來車】",
    "captionText": "【前方路口減速查看】【左右無來車】",
    "startSec": 574.9,
    "endSec": 589.74,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 573.9,
    "clipEndSec": 590.74,
    "tags": [
      "safe_left_right",
      "intersection_scan"
    ],
    "moduleSummary": "回到起終點區域後依序停正、收車、兩段式開門下車並關門。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-058",
    "segmentId": "road-seg-058",
    "moduleId": "return_and_finish_stop",
    "moduleTitle": "回起終點與收車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看】【左右無來車】 注意道路邊線，白線不可壓到",
    "captionText": "【前方路口減速查看】【左右無來車】 注意道路邊線，白線不可壓到",
    "startSec": 589.74,
    "endSec": 603.08,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 588.74,
    "clipEndSec": 604.08,
    "tags": [
      "safe_left_right",
      "intersection_scan"
    ],
    "moduleSummary": "回到起終點區域後依序停正、收車、兩段式開門下車並關門。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-059",
    "segmentId": "road-seg-059",
    "moduleId": "return_and_finish_stop",
    "moduleTitle": "回起終點與收車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看(打右方向燈)左右無來車,後方無來車】",
    "captionText": "【前方路口減速查看(打右方向燈)左右無來車,後方無來車】",
    "startSec": 603.08,
    "endSec": 617.93,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 602.08,
    "clipEndSec": 618.93,
    "tags": [
      "right_signal",
      "safe_left_right",
      "rear_clear",
      "intersection_scan"
    ],
    "moduleSummary": "回到起終點區域後依序停正、收車、兩段式開門下車並關門。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-060",
    "segmentId": "road-seg-060",
    "moduleId": "return_and_finish_stop",
    "moduleTitle": "回起終點與收車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【前方路口減速查看(打左方向燈)左右無來車,後方無來車】",
    "captionText": "【前方路口減速查看(打左方向燈)左右無來車,後方無來車】",
    "startSec": 617.93,
    "endSec": 629.67,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 616.93,
    "clipEndSec": 630.67,
    "tags": [
      "left_signal",
      "safe_left_right",
      "rear_clear",
      "intersection_scan"
    ],
    "moduleSummary": "回到起終點區域後依序停正、收車、兩段式開門下車並關門。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-061",
    "segmentId": "road-seg-061",
    "moduleId": "return_and_finish_stop",
    "moduleTitle": "回起終點與收車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "【打右方向燈,左右無來車,後方無來車】",
    "captionText": "【打右方向燈,左右無來車,後方無來車】",
    "startSec": 629.67,
    "endSec": 640.652,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 628.67,
    "clipEndSec": 641.652,
    "tags": [
      "right_signal",
      "safe_left_right",
      "rear_clear"
    ],
    "moduleSummary": "回到起終點區域後依序停正、收車、兩段式開門下車並關門。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-062",
    "segmentId": "road-seg-062",
    "moduleId": "return_and_finish_stop",
    "moduleTitle": "回起終點與收車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "回到起終點區域，找空位將車輛停正",
    "captionText": "回到起終點區域，找空位將車輛停正",
    "startSec": 640.652,
    "endSec": 648.048,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 639.652,
    "clipEndSec": 649.048,
    "tags": [],
    "moduleSummary": "回到起終點區域後依序停正、收車、兩段式開門下車並關門。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-063",
    "segmentId": "road-seg-063",
    "moduleId": "return_and_finish_stop",
    "moduleTitle": "回起終點與收車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "停妥後依序  打P檔、拉手煞車、 關風扇、關AC、熄火",
    "captionText": "停妥後依序  打P檔、拉手煞車、 關風扇、關AC、熄火",
    "startSec": 650.67,
    "endSec": 671.105,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 649.67,
    "clipEndSec": 672.105,
    "tags": [
      "gear_p",
      "hand_brake"
    ],
    "moduleSummary": "回到起終點區域後依序停正、收車、兩段式開門下車並關門。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-064",
    "segmentId": "road-seg-064",
    "moduleId": "return_and_finish_stop",
    "moduleTitle": "回起終點與收車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "解開安全帶、椅子退後，進行【兩段式開車門】；",
    "captionText": "解開安全帶、椅子退後，進行【兩段式開車門】；",
    "startSec": 671.105,
    "endSec": 680.427,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 670.105,
    "clipEndSec": 681.427,
    "tags": [],
    "moduleSummary": "回到起終點區域後依序停正、收車、兩段式開門下車並關門。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-065",
    "segmentId": "road-seg-065",
    "moduleId": "return_and_finish_stop",
    "moduleTitle": "回起終點與收車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "先看後照鏡，再把頭伸出車外看後方，確認【後方無來車】打開車門15公分【左右無來車】下車",
    "captionText": "先看後照鏡，再把頭伸出車外看後方，確認【後方無來車】打開車門15公分【左右無來車】下車",
    "startSec": 680.427,
    "endSec": 686.354,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 679.427,
    "clipEndSec": 687.354,
    "tags": [
      "safe_left_right",
      "rear_clear"
    ],
    "moduleSummary": "回到起終點區域後依序停正、收車、兩段式開門下車並關門。",
    "sourceBasis": "captions.sbv"
  },
  {
    "bankId": "RT-066",
    "segmentId": "road-seg-066",
    "moduleId": "return_and_finish_stop",
    "moduleTitle": "回起終點與收車",
    "prompt": "依影片字幕與畫面，這一步最正確的作法是？",
    "answerText": "最後關上車門，道路考照動作全部完成",
    "captionText": "最後關上車門，道路考照動作全部完成",
    "startSec": 686.354,
    "endSec": 702.442,
    "clipLeadSeconds": 1.0,
    "clipLagSeconds": 1.0,
    "clipStartSec": 685.354,
    "clipEndSec": 703.442,
    "tags": [],
    "moduleSummary": "回到起終點區域後依序停正、收車、兩段式開門下車並關門。",
    "sourceBasis": "captions.sbv"
  }
];
